### ISSUE TITLE
https なサイトでプルリクの内容をプレビューしたい

### ISSUE THREAD

**Issue by odanado** [perl-users-jp/perl-users-jp.github.io#24]
#2 対応のように事前に https なサイトで動作確認をしたい場合がある
また、レビューを行うときの動作確認で、プレビューサイトがあると便利

Netlify には Deploy Preview 機能があり、プルリク単位でプレビューが可能
https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/
GitHub Actions で静的ファイルを build → Netlify でシュッとプレビューサイトを用意したい

**Comment by odanado** [comment]
ここで試しています
https://github.com/odanado/perl-users-jp.github.io/pull/1
とりあえず、動いています(なぜコメントが複数個ついているけど...)

**Comment by kfly8** [comment]
解決済みなのでクローズします。
