### ISSUE TITLE
はてな記法の脚注をいい感じにする

### ISSUE THREAD

**Issue by kfly8** [perl-users-jp/perl-users-jp.github.io#3]

**Comment by fadlil** [comment]
使ってそうな記事
- https://perl-users-jp.github.io/articles/advent-calendar/2010/meta_adcal/5

関連してそうなコード
https://github.com/perl-users-jp/perl-users-jp.github.io/blob/506060943b8c9d2fbf1385f4d2229dfaa49090a3/lib/PerlUsersJP/Builder.pm#L292

**Comment by fadlil** [comment]
https://github.com/perl-users-jp/perl-users-jp.github.io/blob/506060943b8c9d2fbf1385f4d2229dfaa49090a3/content/articles/advent-calendar/2010/meta_adcal/5.txt#L75-L92
