### ISSUE TITLE
URLにディレクトリを指定したときにindex.htmlが読み込まれない

### ISSUE THREAD

**Issue by argrath** [perl-users-jp/perl-users-jp.github.io#30]
例えば https://perl-users.jp/articles/advent-calendar/2009/ にアクセスすると、そこに置いてある index.html が読み込まれるべきだと思いますが、ファイル一覧が表示されます。

**Comment by AnaTofuZ** [comment]
ご報告ありがとうございます! 対応するプルリクを投げておきました!!!
